apiVersion: v1
data:
  hms_config.json: |-
    {
       "HMSExtendedDefinitions":{
          "Role":[
             "Compute",
             "Service",
             "System",
             "Application",
             "Storage",
             "Management"
          ],
          "SubRole":[
             "Worker",
             "Master",
             "Storage",
             "UAN",
             "Gateway",
             "LNETRouter",
             "Visualization",
             "UserDefined"
          ]
       }
    }
kind: ConfigMap
metadata:
  name: cray-hms-base-config
  namespace: services

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smd-cacert-info
data:
  CA_URI: "{{ .Values.hms_ca_uri }}"

