apiVersion: v2
name: "cray-hms-smd"
version: 7.1.17
description: "Kubernetes resources for cray-hms-smd"
home: "https://github.com/Cray-HPE/hms-smd-charts"
sources:
  - "https://github.com/Cray-HPE/hms-smd"
dependencies:
  - name: cray-service
    version: "~11.0"
    repository: https://artifactory.algol60.net/artifactory/csm-helm-charts
  - name: cray-postgresql
    version: "~1.0"
    repository: https://artifactory.algol60.net/artifactory/csm-helm-charts
maintainers:
  - name: Hardware Management
    url: https://github.com/orgs/Cray-HPE/teams/hardware-management
appVersion: "2.28.0"
annotations:
  artifacthub.io/license: "MIT"
