apiVersion: v2
name: "cray-hms-smd"
version: 7.0.21
description: "Kubernetes resources for cray-hms-smd"
home: "https://github.com/Cray-HPE/hms-smd-charts"
sources:
  - "https://github.com/Cray-HPE/hms-smd"
dependencies:
  - name: cray-service
    version: "~10.0"
    repository: https://artifactory.algol60.net/artifactory/csm-helm-charts
  - name: cray-postgresql
    version: "~1.0"
    repository: https://artifactory.algol60.net/artifactory/csm-helm-charts
maintainers:
  - name: Hardware Management
    url: https://github.com/orgs/Cray-HPE/teams/hardware-management
appVersion: "2.11.17"
annotations:
  artifacthub.io/license: "MIT"
